### ISSUE TITLE
Unit test runner crash after execute

### ISSUE THREAD

**Issue by ignaciolarranaga** [NativeScript/nativescript-unit-test-runner#19] opened 2016-09-28 19:51 UTC
Check for example the sample-Groceries project.

I ran `tns test ios --emulator --watch` and you see the runner execute but at the end:

```
NativeScript / 9.1 (9.1; iPhone): Executed 0 of 3 SUCCESS (0 secs / 0 secs)
NativeScript / 9.1 (9.1; iPhone): Executed 3 of 3 SUCCESS (0.213 secs / 0.002 secs)
Sep 28 16:46:00 MacBook-Pro-de-Ignacio sampleGroceries[11889]: CONSOLE LOG file:///app/tns_modules/nativescript-unit-test-runner/main-view-model.js:258:24: NSUTR: completeAck
NativeScript / 9.1 (9.1; iPhone) ERROR
  Disconnectedundefined
NativeScript / 9.1 (9.1; iPhone): Executed 3 of 3 SUCCESS (0.213 secs / 0.002 secs)
```

And obviously it lose the --watch

**Comment by mica16** [comment] 2017-01-25 23:17
+1 
Same issue for me

**Comment by ishitatsuyuki** [comment] 2017-03-30 03:51
Also occurs on Android. Bump.

**Comment by ishitatsuyuki** [comment] 2017-03-30 04:27
This seems intended: https://github.com/NativeScript/nativescript-unit-test-runner/blob/master/main-view-model.ts#L329

Commenting out will stop the app from suicide but it will crash on the second test anyway. This test runner seems very incomplete.

**Comment by p-3** [comment] 2017-04-29 19:44
same issue for me.

**Comment by dtopuzov** [comment] 2017-05-04 12:16
Closing as duplicate of https://github.com/NativeScript/nativescript-cli/issues/2739.
If you encounter issues with `tns test` please log them in https://github.com/NativeScript/nativescript-cli

**Closed by dtopuzov** 2017-05-04 12:16 UTC

**Comment by ishitatsuyuki** [comment] 2017-05-04 12:26
@dtopuzov Why are you moving this? This is simply the implementation fault of test runner and there's nothing to do with the CLI.
